### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by mibus** [Jakz/retro8#29]
It'd be really useful to have some build instructions (esp. for different platforms) in the README.

e.g. there's a Makefile in the git repository, but it builds a .so file rather than a binary. `cmake && make` stomps over the Makefile but builds a binary.

Is there a makefile for building against SDL1.2 with my cross-compiler in `/opt/mipsel-linux-uclibc`? (I want to build an opk for retrofw).

Thanks!!

**Comment by mibus** [comment]
FWIW, this seems to work...

I edited CMakeLists.txt to replace the OPENDINGUX sysroot with one for my system:
+  set(CMAKE_SYSROOT "/opt/mipsel-linux-uclibc/mipsel-buildroot-linux-uclibc/sysroot")

Generated new Makefiles:
```
rm -rf CMakeFiles/ CMakeCache.txt
CROSS=/opt/mipsel-linux-uclibc/bin/mipsel-buildroot-linux-uclibc- cmake -DOPENDINGUX=ON -DFUNKEY_S=ON .
```

Editing projects/build_opk_od.sh to deploy this desktop file instead (copied from the gameblabla fork):
```
[Desktop Entry]
Type=Application
Name=Retro8
Comment=PICO-8 Emulator
Exec=retro8 %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true
X-OD-Filter=.png,.p8
```

...and the resulting opk seems to work!

**Comment by Jakz** [comment]
I consider this closed with new instruction and updated cmake. Hopefully in the future the cmake script will be enhanced to contain instructions.
