### ISSUE TITLE
Build new Retroarch Android Core

### ISSUE THREAD

**Issue by MonkoftheFunk** [Jakz/retro8#36]
@phcoder curious could you or tell what the make command is to build a 32 or 64 libretro core for android, hoping for a 0.2.* build?
Thanks

**Comment by phcoder** [comment]
This is not a bug. The answer is "ndk-build" and you'll get all the variants

**Comment by MonkoftheFunk** [comment]
yup ran ndk-build in /jni folder and it made all the varients in libs folder, going to try it out, thanks again for reply

**Comment by MonkoftheFunk** [comment]
They load but they don't have info in the core so the content doesn't open with them, thoughts?

**Comment by MonkoftheFunk** [comment]
They load but they don't have info in the core so the content doesn't open with them, thoughts?
@phcoder (thanks again)

**Comment by MonkoftheFunk** [comment]
![Screenshot_2022-07-23-13-38-08-679](https://user-images.githubusercontent.com/639841/180622092-fc8fc7ed-4e9d-44a8-9062-fd8430c1be7d.png)
