### ISSUE TITLE
Retro8 does not allow blank newlines in carts

### ISSUE THREAD

**Issue by p-sam** [Jakz/retro8#9]
Example cart: [A Doukutsu Demake.p8.txt](https://github.com/Jakz/retro8/files/4148106/A.Doukutsu.Demake.p8.txt)

This cart has a newline between the `__gfx__` section and the `__gff__` section, which cause an assert to fail, instead of just skipping the line like PICO-8 does

**Comment by gouchi** [comment]
Same issue with [squashy.p8](https://raw.githubusercontent.com/Kartones/pico-8/master/squashy.p8).

**Comment by Jakz** [comment]
Fixed in https://github.com/Jakz/retro8/commit/c1e696cdd7723af889878c46d8fcbdf170bf5633
